---
upgrade_packages: false

vm_config:
  memory: 1024
  cores: 1
  disk_size: "40G"
  disk_storage: "local-zfs"
  username: "vm"
  password: "password"
  hagroup: ""


pve_nodes:
  - ajaya-alpha

pve_credentials:
  api_endpoint: "https://192.168.1.21:8006/api2/json"
  api_token_id: "root@pam!terraform"
  api_secret: "2f398da9-ee3a-4664-8993-27e9f9d0531a"

ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgR+DbPMll+ax1L1oklwfZnNqabHbNlVuCQGZaoDftW9OzgGqMkpq9LxjL+sIg+lA5oSAgx2+YzJ1PDw9PSHzipkVSJe27znC2aPakQyHulab1OlAqRUjJRnH1DdLNNmary6AoLBhbN4nYWKD7arhDivI9NcXUceHKENmo30ueKXpAUpYAOabf7oxDP9+w6Gz0BASKpW92ZuwIZGUmschfp75PTg9Phtoq/widZcE3AmYQ8bXPfrTAvVJc2VaYijp908atAfz6cb4vqpPV+0iLR7PHDJBvDuOmiaMrg+A7S/DCovn6D4TPAENejPXq1HRCaF3f+PtTwJmLFos2B1iZlkR1yofyT26dp/nLOMMDtHM/NWFjH0ui7ihmrQf17Khr20++8PLqoEqmclrUDj1RdoOFsrDJCSt2mgFhxY/FjRc1G3O69Ds9G3UxKIaYbjnsPctf3uc+LKl1hFUZKe9IKWKq/wSEJ5FLSTGWWblsS7LQk5d1WjG/xItGFa3L7Dc= root@AutController"
ssh_private_key_path: "/home/ubuntu/.sshkey/cloudinit"

gateways:
  - uuid: codevm
    comments: "Customer 1 Inc."
    nodes:
      - ip_gateway: 192.168.1.1
        ip_address: 192.168.29.91
        ip_cidr: 24
    dns: 127.0.1.1
    state: present
